# Maven
# Build your Java projects and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

variables:
  azureSubscription: 'RMPM'
  appName_JSE: 'LinuxJSE'

jobs:
  - job: MavenBuild
    steps:
    - task: Maven@3
      displayName: 'Maven $(mavenPOMFile)'
      inputs:
        mavenPomFile: sampleWebApp/pom.xml

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/*.war'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts: drop'
      inputs:
        PathtoPublish: $(build.artifactstagingdirectory)

  
  - job: Deploy
    dependsOn: MavenBuild
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: drop
    - task: AzureWebApp@1
      displayName: 'Azure Web App Deploy: LinuxJSEApp'
      inputs:
        azureSubscription: $(azureSubscription)
        appType: webAppLinux
        appName: $(appName_JSE)
        package: '$(build.artifactstagingdirectory)/**/target/*.war'
