# Maven
# Build your Java projects and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

variables:
  azureSubscription: 'JavaSpring - Service Endpoint'
  appName_TomCat: 'LinuxTomcatApp'

jobs:
  - job: MavenBuild
    steps:
    - task: Maven@3
      displayName: 'Maven $(mavenPOMFile)'
      inputs:
        mavenPomFile: sampleWebApp/pom.xml
        testResultsFiles: '**/TEST*.xml'
        mavenAuthenticateFeed: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts: drop'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)'
  
  - job: Deploy
    dependsOn: MavenBuild
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: drop
    - task: AzureWebApp@1
      displayName: 'Azure Web App Deploy: LinuxTomcatApp'
      inputs:
        azureSubscription: $(azureSubscription)
        appType: webAppLinux
        appName: $(appName_TomCat)
        package: '$(System.ArtifactsDirectory)/**/target/*.war'
        runtimeStack: 'TOMCAT|8.5-java11'
        startUpCommand: 'mvn spring-boot:run'
